Repository githubschool/fast-track, pull requests merged in 2021-11, with the labels that each got.

#8 Gusshawstewart add caption
  _slides/02-gusshawstewart.md
Labels: documentation, enhancement, staging

#17 updates caption for JasonCubic
  _slides/05-JasonCubic.md
Labels: documentation

#9 Updated Caption for 06-SyedAanif
  _slides/06-SyedAanif.md
Labels: documentation

#10 soolch updates caption
  _slides/14-soolch.md
Labels: unicorn

#11 update caption
  _slides/10-ralsinn.md
Labels: documentation

#20 updated caption
  _slides/03-Deepika-tmna.md
Labels: documentation

#12 update caption
  _slides/12-roshvin.md
Labels: good first issue
